from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from apk_docforge.agents.base import AgentContext, BaseAgent
from apk_docforge.renderers.markdown import render_doc, render_report, write_markdown
from apk_docforge.tools.llm_deepseek import DeepSeekDocumentationClient


class DocumentationAgent(BaseAgent):
    name = "DocumentationAgent"
    output_files = ("report.md", "docs/")

    def run(self) -> AgentContext:
        data = build_documentation_context(self.context)
        llm_result = DeepSeekDocumentationClient().generate_markdown(self._bounded_llm_context(data))
        llm_metadata = {
            "provider": llm_result.provider,
            "enabled": llm_result.enabled,
            "status": llm_result.status,
            "model": llm_result.model,
            "error": llm_result.error,
            "policy": "No APK binaries or full decompiled source are sent; only bounded JSON summaries and evidence refs.",
        }
        self.context.data["documentation_llm"] = llm_metadata

        local_report = render_report(data)
        report = self._combine_report(local_report, llm_result.content)
        write_markdown(self.path("report.md"), report)
        self._write_docs(data, llm_metadata)
        self.write_json(
            "documentation_summary.json",
            {
                "schema_version": "1.0",
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "report_path": str(self.path("report.md")),
                "docs_dir": str(self.context.docs_dir),
                "llm": llm_metadata,
            },
        )
        self.context.data["documentation_context"] = data
        return self.context

    def _combine_report(self, local_report: str, llm_content: str | None) -> str:
        if not llm_content:
            return local_report
        return (
            f"{local_report.rstrip()}\n\n"
            "## DeepSeek Draft Addendum\n\n"
            "The following section was generated by DeepSeek from bounded JSON summaries only. "
            "Treat JSON artifacts as the source of truth.\n\n"
            f"{llm_content.strip()}\n"
        )

    def _write_docs(self, data: dict[str, Any], llm_metadata: dict[str, Any]) -> None:
        docs = {
            "00_resumen_ejecutivo.md": self._executive_summary(data, llm_metadata),
            "01_identidad_app.md": self._identity_doc(data),
            "02_mapa_funcional.md": self._features_doc(data),
            "02b_brief_reconstruccion_codex.md": self._reconstruction_doc(data),
            "03_pantallas_y_botones.md": self._screens_doc(data),
            "04_conexiones_y_sdks.md": self._connections_doc(data),
            "05_permisos_privacidad.md": self._permissions_doc(data),
            "06_hallazgos_seguridad.md": self._security_doc(data),
            "06b_controles_y_fronteras.md": self._control_boundaries_doc(data),
            "07_matriz_pruebas.md": self._test_matrix_doc(data),
            "08_backlog_recomendado.md": self._backlog_doc(data),
            "09_limitaciones.md": self._limitations_doc(data, llm_metadata),
        }
        for filename, body in docs.items():
            title = Path(filename).stem.replace("_", " ").title()
            write_markdown(self.context.docs_dir / filename, render_doc(title, body))

    def _bounded_llm_context(self, data: dict[str, Any]) -> dict[str, Any]:
        return {
            "identity": data.get("identity", {}),
            "app_understanding": data.get("app_understanding", {}),
            "source_metadata": data.get("source_metadata", {}),
            "reconstruction_brief": data.get("reconstruction_brief", {}),
            "features": data.get("features", [])[:50],
            "screens": data.get("screens", [])[:50],
            "endpoints": data.get("endpoints", [])[:80],
            "permissions": data.get("permissions", [])[:80],
            "findings": data.get("findings", [])[:80],
            "protection_controls": data.get("protection_controls", [])[:50],
            "authorization_boundaries": data.get("authorization_boundaries", [])[:50],
            "bypass_policy": data.get("bypass_policy", {}),
            "limitations": [
                "Static-only analysis unless explicitly configured otherwise.",
                "No APK binary, screenshots, or decompiled source included in this LLM context.",
                "Evidence refs point to local files in the analysis output directory.",
            ],
        }

    def _executive_summary(self, data: dict[str, Any], llm_metadata: dict[str, Any]) -> str:
        identity = data["identity"]
        understanding = data.get("app_understanding", {})
        reconstruction = data.get("reconstruction_brief", {})
        flows = understanding.get("core_flows", [])
        return "\n".join(
            [
                f"- App: {identity.get('app_name') or identity.get('package_name') or 'unknown'}",
                f"- Package: {identity.get('package_name') or 'unknown'}",
                f"- Qué es: {understanding.get('what_it_is') or 'unknown'}",
                f"- Para qué sirve: {understanding.get('purpose') or 'unknown'}",
                f"- Objetivo para Codex: {reconstruction.get('codex_goal') or 'unknown'}",
                f"- Flujos principales: {', '.join(item.get('name', 'unknown') for item in flows[:8]) or 'unknown'}",
                f"- Analysis mode: {identity.get('mode') or 'static'}",
                f"- Features inferred: {len(data.get('features', []))}",
                f"- Screens mapped: {len(data.get('screens', []))}",
                f"- Network endpoints/domains: {len(data.get('endpoints', []))}",
                f"- Security findings: {len(data.get('findings', []))}",
                f"- Protection controls: {len([item for item in data.get('protection_controls', []) if item.get('status') != 'unknown'])}",
                f"- Documentation provider: {llm_metadata.get('provider')} ({llm_metadata.get('status')})",
            ]
        )

    def _identity_doc(self, data: dict[str, Any]) -> str:
        identity = data["identity"]
        return "\n".join(f"- {key}: {value or 'unknown'}" for key, value in identity.items())

    def _features_doc(self, data: dict[str, Any]) -> str:
        rows = []
        understanding = data.get("app_understanding", {})
        if understanding:
            rows.extend(
                [
                    f"- Qué es: {understanding.get('what_it_is') or 'unknown'}",
                    f"- Para qué sirve: {understanding.get('purpose') or 'unknown'}",
                    f"- Confidence: {understanding.get('confidence_score', 'unknown')}",
                    "",
                    "## Flujos principales",
                ]
            )
            flows = understanding.get("core_flows", [])
            rows.extend(
                f"- {item.get('name')}: {item.get('description')} "
                f"confidence={item.get('confidence_score')}"
                for item in flows
            )
            rows.append("")
        if not data.get("features"):
            rows.append("No se detectaron funcionalidades técnicas adicionales con evidencia suficiente.")
            return "\n".join(rows)
        rows.append("## Señales técnicas")
        rows.extend(
            f"- {item['name']} ({item['category']}): {item['description']} "
            f"confidence={item.get('confidence_score', item.get('confidence'))}"
            for item in data["features"]
        )
        return "\n".join(rows)

    def _reconstruction_doc(self, data: dict[str, Any]) -> str:
        brief = data.get("reconstruction_brief", {})
        if not brief:
            return "No se genero brief de reconstruccion."
        rows = [
            f"- Objetivo Codex: {brief.get('codex_goal') or 'unknown'}",
            "",
            "## Alcance MVP recomendado",
        ]
        rows.extend(f"- {item}" for item in brief.get("recommended_mvp_scope", []))
        rows.extend(["", "## Pantallas a reconstruir"])
        rows.extend(
            f"- {item.get('name')}: {item.get('description')}"
            for item in brief.get("screen_blueprint", [])
        )
        rows.extend(["", "## Modelos de datos"])
        rows.extend(f"- {item}" for item in brief.get("core_data_models", []))
        rows.extend(["", "## Fuera de alcance"])
        rows.extend(f"- {item}" for item in brief.get("out_of_scope", []))
        return "\n".join(rows)

    def _screens_doc(self, data: dict[str, Any]) -> str:
        if not data.get("screens"):
            return "No se mapearon pantallas estáticas."
        return "\n".join(
            f"- {item['name']}: source={item.get('source')}, elements={item.get('ui_element_count', 0)}, "
            f"confidence={item.get('confidence')}"
            for item in data["screens"]
        )

    def _connections_doc(self, data: dict[str, Any]) -> str:
        endpoints = data.get("endpoints", [])
        if not endpoints:
            return "No se detectaron dominios o endpoints en cadenas estáticas."
        return "\n".join(
            f"- {item.get('url') or item.get('domain')}: type={item.get('type')}, confidence={item.get('confidence')}"
            for item in endpoints[:100]
        )

    def _permissions_doc(self, data: dict[str, Any]) -> str:
        if not data.get("permissions"):
            return "No se observaron permisos en el manifiesto o el manifiesto no fue parseable."
        return "\n".join(
            f"- {item['name']}: risk={item['risk']}, justification={item['justification_probable']}"
            for item in data["permissions"]
        )

    def _security_doc(self, data: dict[str, Any]) -> str:
        if not data.get("findings"):
            return "No se generaron hallazgos de seguridad con evidencia en el análisis estático."
        return "\n".join(
            f"- [{item['severity']}] {item['title']}: {item['recommendation']}"
            for item in data["findings"]
        )

    def _control_boundaries_doc(self, data: dict[str, Any]) -> str:
        controls = data.get("protection_controls", [])
        boundaries = data.get("authorization_boundaries", [])
        policy = data.get("bypass_policy", {})
        rows = [
            "- Bypass implementado: false",
            "- Bypass intentado: false",
            f"- Politica: {policy.get('reason') or 'Los controles se documentan sin evadirlos.'}",
            "",
            "## Controles detectados",
        ]
        observed = [item for item in controls if item.get("status") != "unknown"]
        if not observed:
            rows.append("- No se detectaron controles de proteccion con evidencia estatica suficiente.")
        else:
            rows.extend(
                f"- {item['name']} ({item['status']}): {item['recommendation']} "
                f"confidence={item.get('confidence_score', item.get('confidence'))}"
                for item in observed
            )
        rows.extend(["", "## Fronteras de autorizacion"])
        if not boundaries:
            rows.append("- No se observaron fronteras adicionales con evidencia.")
        else:
            rows.extend(
                f"- {item['name']}: accion permitida={item['allowed_audit_action']}; "
                f"accion bloqueada={item['blocked_action']}"
                for item in boundaries
            )
        return "\n".join(rows)

    def _test_matrix_doc(self, data: dict[str, Any]) -> str:
        rows = []
        for screen in data.get("screens", [])[:10]:
            rows.append(f"- Pantalla {screen['name']}: validar render y acciones no destructivas en emulador.")
        for feature in data.get("features", [])[:10]:
            rows.append(f"- Funcionalidad {feature['name']}: validar flujo con datos de prueba.")
        return "\n".join(rows) if rows else "No hay matriz de pruebas sugerida por falta de evidencia."

    def _backlog_doc(self, data: dict[str, Any]) -> str:
        rows = [
            "- Completar análisis dinámico autorizado para pantallas y navegación.",
            "- Revisar hallazgos medium/high antes de distribución.",
            "- Documentar justificación de permisos sensibles.",
            "- Validar endpoints activos y clasificación de datos transmitidos.",
        ]
        if not data.get("features"):
            rows.append("- Repetir análisis con jadx/apktool instalados para mejorar inferencia de funcionalidades.")
        return "\n".join(rows)

    def _limitations_doc(self, data: dict[str, Any], llm_metadata: dict[str, Any]) -> str:
        rows = [
            "- Fase 1 es static-only.",
            "- No se ejecuta APK ni navegación dinámica.",
            "- No se hacen bypasses de pinning, login, pagos, DRM, licencias ni anti-tamper.",
            "- Los flujos detrás de login quedan unknown.",
            f"- DeepSeek: {llm_metadata.get('status')} ({llm_metadata.get('error') or 'sin error'}).",
        ]
        missing = [name for name, meta in data.get("tools", {}).items() if not meta.get("available")]
        if missing:
            rows.append(f"- Herramientas faltantes: {', '.join(missing)}.")
        return "\n".join(rows)


def build_documentation_context(context: AgentContext) -> dict[str, Any]:
    artifact = context.data.get("artifact", {})
    manifest = context.data.get("manifest", {})
    app = manifest.get("application", {})
    source_metadata = context.data.get("source_metadata", {})
    candidate = artifact.get("candidate", {}) if isinstance(artifact.get("candidate"), dict) else {}
    return {
        "schema_version": "1.0",
        "identity": {
            "app_name": source_metadata.get("app_name") or candidate.get("app_name") or app.get("label"),
            "package_name": manifest.get("package_name"),
            "version_name": manifest.get("version_name"),
            "version_code": manifest.get("version_code"),
            "min_sdk": manifest.get("min_sdk"),
            "target_sdk": manifest.get("target_sdk"),
            "certificate": "unknown",
            "source": artifact.get("source_type", "local_file"),
            "sha256": artifact.get("sha256"),
            "analysis_date": context.analysis_started_at,
            "mode": context.mode,
        },
        "features": context.data.get("features", []),
        "app_understanding": context.data.get("app_understanding", {}),
        "source_metadata": context.data.get("source_metadata", {}),
        "reconstruction_brief": context.data.get("reconstruction_brief", {}),
        "screens": context.data.get("static_screens", []),
        "screens_dynamic": context.data.get("screens_dynamic", []),
        "ui_elements": context.data.get("ui_elements_static", []),
        "ui_elements_dynamic": context.data.get("ui_elements_dynamic", []),
        "navigation_dynamic": context.data.get("navigation_graph_dynamic", []),
        "blocked_flows": context.data.get("blocked_flows_dynamic", []),
        "dynamic_session": context.data.get("dynamic_session", {}),
        "endpoints": context.data.get("network_endpoints", []),
        "domains": context.data.get("domains", []),
        "observed_sdks": [
            item["name"] for item in context.data.get("sdk_detection", []) if item.get("status") == "observed"
        ],
        "api_clients": context.data.get("api_clients", []),
        "permissions": context.data.get("permissions", []),
        "components": context.data.get("components", {}),
        "deep_links": context.data.get("deep_links", []),
        "findings": context.data.get("security_findings", []),
        "privacy_risks": context.data.get("privacy_risks", []),
        "protection_controls": context.data.get("protection_controls", []),
        "authorization_boundaries": context.data.get("authorization_boundaries", []),
        "bypass_policy": context.data.get("bypass_policy", {}),
        "tools": context.tools,
    }
